apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cubejs.fullname" . }}
  labels:
    {{- include "cubejs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cubejs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cubejs.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
        - name: model
          emptyDir: {}
      {{- if .Values.model }}
      initContainers:
        - name: fetch-model
          image: inseefrlab/onyxia-base:latest
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.resourcesInit | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          command:
            - sh
            - -c
            - |
              echo 'fetch the model';
              mkdir -p /model && wget -O /model/model.yml {{ .Values.model }} || true
          volumeMounts:
          - name: model
            mountPath: "/model"
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.service.image.version }}
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
          - name: CUBEJS_DB_TYPE
            value: duckdb
          - name: CUBEJS_DB_DUCKDB_S3_ACCESS_KEY_ID
            value: {{ .Values.s3.accessKeyId }}
          - name: CUBEJS_DB_DUCKDB_S3_SECRET_ACCESS_KEY
            value: {{ .Values.s3.secretAccessKey }}
          - name: CUBEJS_DB_DUCKDB_S3_ENDPOINT
            value: {{ .Values.s3.endpoint }}
          - name: CUBEJS_DB_DUCKDB_S3_REGION
            value: {{ .Values.s3.defaultRegion }}
          - name: CUBEJS_DB_DUCKDB_S3_SESSION_TOKEN
            value: {{ .Values.s3.sessionToken }}
            {{- if .Values.s3.pathStyleAccess }}
          - name: CUBEJS_DB_DUCKDB_S3_URL_STYLE
            value: path
            {{- end }}
          - name: CUBEJS_DB_DUCKDB_EXTENSIONS
            value: httpfs
          - name: CUBEJS_CONCURRENCY
            value: "30"
          - name: CUBEJS_DEV_MODE
            value: "true"
          - name: CUBEJS_PG_SQL_PORT
            value: {{ .Values.sqlApi.targetPort | quote }}
          - name: CUBEJS_SQL_USER
            value: {{ .Values.sqlApi.username }}
          - name: CUBEJS_SQL_PASSWORD
            value: {{ .Values.sqlApi.password }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: sql-api
              containerPort: {{ .Values.sqlApi.targetPort}}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.model }}
          volumeMounts:
            - name: model
              mountPath: /cube/conf/model
          {{- end }}
