{{- if (.Values.ingress).enabled -}}
{{- $fullName := include "cubejs.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cubejs.labels" . | nindent 4 }}
  annotations: 
    cert-manager.io/cluster-issuer: "developpement-insee-fr"  
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ $fullName }}-cert    
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
