apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "cubejs.fullname" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce


